### ISSUE TITLE
REPL and "NSWindow drag regions should only be invalidated on the Main Thread!"

### ISSUE THREAD

**Issue by oshyshko** [haskell-game/sdl2#200]
I am trying to set up a REPL for an SDL2 project.

I am getting `"NSWindow drag regions should only be invalidated on the Main Thread!"` via `getError` after calling `createWindow` from REPL.

Following [a note about using REPL](https://github.com/haskell-game/sdl2#development), I have `-fPIC` in settings in `package.yaml`:
```yaml
executables:
  demo:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -fPIC
    dependencies:
    - base
    - sdl2
```

```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import SDL
import SDL.Internal.Exception (getError)

main :: IO ()
main = do
    initializeAll
    window <- createWindow "Demo" defaultWindow

    print window
    getError >>= print

    renderer <- createRenderer window (-1) defaultRenderer
```

But this doesn't seem to work:
```bash
$ stack repl
...
> main
Window 0x0000000000000000
"NSWindow drag regions should only be invalidated on the Main Thread!"
*** Exception: SDLCallFailed {sdlExceptionCaller = "SDL.Video.createRenderer", sdlFunction = "SDL_CreateRenderer", sdlExceptionError = "Invalid window"}
```
Any suggestions on how to make REPL work?

Environment:
- OS X 10.14.5
- stack 1.9.3, resolver lts-13.27 (GHC 8.6.5)
- sdl 2.0.9_1
